import React from 'react';
import { ArticleData } from '../types';

interface ArticleViewProps {
  article: ArticleData;
  imageUrl: string | null;
  onBack: () => void;
}

const ArticleView: React.FC<ArticleViewProps> = ({ article, imageUrl, onBack }) => {
  return (
    <article className="max-w-6xl mx-auto px-4 md:px-8 pb-20">
      <button 
        onClick={onBack}
        className="mb-6 font-sans-ui text-xs font-bold uppercase tracking-widest text-gray-500 hover:text-black transition-colors flex items-center gap-2"
      >
        ← Back to Front Page
      </button>

      <header className="mb-8 text-center max-w-4xl mx-auto">
        <h1 className="font-headline text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 leading-tight mb-4">
          {article.headline}
        </h1>
        <h2 className="font-body text-xl md:text-2xl text-gray-600 italic mb-6 font-light">
          {article.subheadline}
        </h2>
        
        <div className="flex flex-col md:flex-row items-center justify-center gap-2 md:gap-6 text-sm font-sans-ui border-y border-gray-200 py-3">
          <span className="font-bold text-gray-900 uppercase">By {article.author}</span>
          <span className="hidden md:inline text-gray-300">•</span>
          <span className="text-gray-600 uppercase">{article.location}</span>
          <span className="hidden md:inline text-gray-300">•</span>
          <span className="text-gray-600">{article.date}</span>
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Main Content Area */}
        <div className="lg:col-span-8 lg:col-start-3 space-y-6">
          
          {imageUrl ? (
            <figure className="w-full mb-8">
              <img 
                src={imageUrl} 
                alt={article.imagePrompt} 
                className="w-full h-auto object-cover max-h-[600px]" // Removed shadow/rounded for stricter newspaper look
              />
              <figcaption className="mt-2 text-sm text-gray-500 font-sans-ui text-right">
                Generated by Gemini 3 Pro (Nano Banana Pro)
              </figcaption>
            </figure>
          ) : (
            <div className="w-full h-64 bg-gray-100 flex items-center justify-center text-gray-400 italic font-serif mb-8">
              Image unavailable
            </div>
          )}

          <div className="font-body text-lg md:text-xl leading-relaxed text-gray-800 space-y-6 text-justify">
            {article.paragraphs.map((para, idx) => (
              <p key={idx} className={idx === 0 ? "first-letter:text-5xl first-letter:font-bold first-letter:float-left first-letter:mr-3 first-letter:mt-[-4px] first-letter:font-header" : ""}>
                {para}
              </p>
            ))}
          </div>

          {/* Sources Section */}
          {article.sources.length > 0 && (
            <div className="mt-12 pt-6 border-t border-gray-200">
              <h3 className="font-sans-ui text-sm font-bold uppercase tracking-widest mb-4 text-gray-900">Sources & References</h3>
              <ul className="space-y-2">
                {article.sources.map((source, idx) => (
                  <li key={idx}>
                    <a 
                      href={source.uri} 
                      target="_blank" 
                      rel="noreferrer"
                      className="font-sans-ui text-sm text-gray-600 hover:underline truncate block"
                    >
                      {idx + 1}. {source.title}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>
    </article>
  );
};

export default ArticleView;